In [1]:
library(readxl)

In [3]:
dat1 <- read_excel("../data/auto-mpg.xlsx")

In [82]:
t(dat1)

[,1]                      [,2]              [,3]              
mpg          18.0                      15.0              18.0              
cylinder     8                         8                 8                 
displacement 307.0                     350.0             318.0             
horsepower   130                       165               150               
weight       3504                      3693              3436              
acceleration 12.0                      11.5              11.0              
year         70                        70                70                
origin       1                         1                 1                 
name         chevrolet chevelle malibu buick skylark 320 plymouth satellite
             [,4]          [,5]        [,6]             [,7]            
mpg          16.0          17.0        15.0             14.0            
cylinder     8             8           8                8               
displacement 304.0         302.0       429.0            454.0           
horsepower   150           140         198              220             
weight       3433          3449        4341             4354            
acceleration 12.0          10.5        10.0              9.0            
year         70            70          70               70              
origin       1             1           1                1               
name         amc rebel sst ford torino ford galaxie 500 chevrolet impala
             [,8]              [,9]             [,10]              [,11]
mpg          14.0              14.0             15.0               ⋯    
cylinder     8                 8                8                  ⋯    
displacement 440.0             455.0            390.0              ⋯    
horsepower   215               225              190                ⋯    
weight       4312              4425             3850               ⋯    
acceleration  8.5              10.0              8.5               ⋯    
year         70                70               70                 ⋯    
origin       1                 1                1                  ⋯    
name         plymouth fury iii pontiac catalina amc ambassador dpl ⋯    
             [,12]                      [,13]          [,14]           
mpg          26.0                       22.0           32.0            
cylinder     4                          6              4               
displacement 156.0                      232.0          144.0           
horsepower   92                         112            96              
weight       2585                       2835           2665            
acceleration 14.5                       14.7           13.9            
year         82                         82             82              
origin       1                          1              3               
name         chrysler lebaron medallion ford granada l toyota celica gt
             [,15]             [,16]            [,17]           [,18]    
mpg          36.0              27.0             27.0            44.0     
cylinder     4                 4                4               4        
displacement 135.0             151.0            140.0            97.0    
horsepower   84                90               86              52       
weight       2370              2950             2790            2130     
acceleration 13.0              17.3             15.6            24.6     
year         82                82               82              82       
origin       1                 1                1               2        
name         dodge charger 2.2 chevrolet camaro ford mustang gl vw pickup
             [,19]         [,20]       [,21]     
mpg          32.0          28.0        31.0      
cylinder     4             4           4         
displacement 135.0         120.0       119.0     
horsepower   84            79          82        
weight       2295          2625        2720      
acceleration 11.6          18.6  

In [83]:
dat.base5<-dat1

In [84]:
t(dat.base5)

[,1]                      [,2]              [,3]              
mpg          18.0                      15.0              18.0              
cylinder     8                         8                 8                 
displacement 307.0                     350.0             318.0             
horsepower   130                       165               150               
weight       3504                      3693              3436              
acceleration 12.0                      11.5              11.0              
year         70                        70                70                
origin       1                         1                 1                 
name         chevrolet chevelle malibu buick skylark 320 plymouth satellite
             [,4]          [,5]        [,6]             [,7]            
mpg          16.0          17.0        15.0             14.0            
cylinder     8             8           8                8               
displacement 304.0         302.0       429.0            454.0           
horsepower   150           140         198              220             
weight       3433          3449        4341             4354            
acceleration 12.0          10.5        10.0              9.0            
year         70            70          70               70              
origin       1             1           1                1               
name         amc rebel sst ford torino ford galaxie 500 chevrolet impala
             [,8]              [,9]             [,10]              [,11]
mpg          14.0              14.0             15.0               ⋯    
cylinder     8                 8                8                  ⋯    
displacement 440.0             455.0            390.0              ⋯    
horsepower   215               225              190                ⋯    
weight       4312              4425             3850               ⋯    
acceleration  8.5              10.0              8.5               ⋯    
year         70                70               70                 ⋯    
origin       1                 1                1                  ⋯    
name         plymouth fury iii pontiac catalina amc ambassador dpl ⋯    
             [,12]                      [,13]          [,14]           
mpg          26.0                       22.0           32.0            
cylinder     4                          6              4               
displacement 156.0                      232.0          144.0           
horsepower   92                         112            96              
weight       2585                       2835           2665            
acceleration 14.5                       14.7           13.9            
year         82                         82             82              
origin       1                          1              3               
name         chrysler lebaron medallion ford granada l toyota celica gt
             [,15]             [,16]            [,17]           [,18]    
mpg          36.0              27.0             27.0            44.0     
cylinder     4                 4                4               4        
displacement 135.0             151.0            140.0            97.0    
horsepower   84                90               86              52       
weight       2370              2950             2790            2130     
acceleration 13.0              17.3             15.6            24.6     
year         82                82               82              82       
origin       1                 1                1               2        
name         dodge charger 2.2 chevrolet camaro ford mustang gl vw pickup
             [,19]         [,20]       [,21]     
mpg          32.0          28.0        31.0      
cylinder     4             4           4         
displacement 135.0         120.0       119.0     
horsepower   84            79          82        
weight       2295          2625        2720      
acceleration 11.6          18.6  

In [85]:
m <- mean(dat.base5$weight)
m

[1] 2970.425

In [86]:
# 두개로 범주를 나눌 때는 ifelse를 사용하면된다.
dat.base5$weight_rank <- ifelse(dat.base5$weight >= m, 1 , 0)

In [87]:
t(dat.base5$weight_rank)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 1    1    1    1    1    1    1    1    1    1     ⋯     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 0     0     0     0     0     0     0

In [88]:
# 몸무게를 5분위수로 나눠서 구하고 양끝에 최소(0)와 최대(Inf)를 넣는다.
q <- c(0)
for(i in seq(from=0, to=1, length=5)){
    q <- c(q, as.integer(quantile(dat.base5$weight, i)))
}
q <- c(q, Inf)
q

[1]    0 1613 2223 2803 3608 5140  Inf

In [117]:
dat.base5$weight_cut <- cut(dat.base5$weight, breaks=q)
t(as.integer(dat.base5$weight_cut))

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 4    5    4    4    4    5    5    5    5    5     ⋯     3     4     3    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 3     4     3     2     3     3     3

In [118]:
t(dat.base5$weight_cut)

[,1]               [,2]                [,3]              
[1,] (2.8e+03,3.61e+03] (3.61e+03,5.14e+03] (2.8e+03,3.61e+03]
     [,4]               [,5]               [,6]               
[1,] (2.8e+03,3.61e+03] (2.8e+03,3.61e+03] (3.61e+03,5.14e+03]
     [,7]                [,8]                [,9]               
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,10]               [,11]              [,12]              
[1,] (3.61e+03,5.14e+03] (2.8e+03,3.61e+03] (3.61e+03,5.14e+03]
     [,13]               [,14]              [,15]             
[1,] (3.61e+03,5.14e+03] (2.8e+03,3.61e+03] (2.22e+03,2.8e+03]
     [,16]              [,17]              [,18]             
[1,] (2.8e+03,3.61e+03] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03]
     [,19]               [,20]               [,21]             
[1,] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03] (2.22e+03,2.8e+03]
     [,22]              [,23]              [,24]             
[1,] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03]
     [,25]              [,26]               [,27]              
[1,] (2.22e+03,2.8e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,28]               [,29]               [,30]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (1.61e+03,2.22e+03]
     [,31]              [,32]              [,33]              
[1,] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03] (1.61e+03,2.22e+03]
     [,34]              [,35]              [,36]             
[1,] (2.22e+03,2.8e+03] (2.8e+03,3.61e+03] (2.8e+03,3.61e+03]
     [,37]              [,38]              [,39]              
[1,] (2.8e+03,3.61e+03] (2.8e+03,3.61e+03] (3.61e+03,5.14e+03]
     [,40]               [,41]               [,42]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,43]               [,44]               [,45]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,46]              [,47]              [,48]             
[1,] (2.8e+03,3.61e+03] (2.22e+03,2.8e+03] (2.8e+03,3.61e+03]
     [,49]              [,50]               [,51]              
[1,] (2.8e+03,3.61e+03] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03]
     [,52]               [,53]               [,54]               [,55]       
[1,] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03] (0,1.61e+03]
     [,56]               [,57]               [,58]             
[1,] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03] (2.22e+03,2.8e+03]
     [,59]               [,60]              [,61]             
[1,] (1.61e+03,2.22e+03] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03]
     [,62]              [,63]               [,64]              
[1,] (2.22e+03,2.8e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,65]               [,66]               [,67]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,68]               [,69]               [,70]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,71]               [,72]              [,73]              
[1,] (3.61e+03,5.14e+03] (2.22e+03,2.8e+03] (3.61e+03,5.14e+03]
     [,74]               [,75]               [,76]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,77]              [,78]              [,79]             
[1,] (2.8e+03,3.61e+03] (2.22e+03,2.8e+03] (2.8e+03,3.61e+03]
     [,80]               [,81]              [,82]             
[1,] (1.61e+03,2.22e+03] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03]
     [,83]              [,84]               [,85]              
[1,] (2.22e+03,2.8e+03] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03]
     [,86]               [,87]               [,88]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,89]               [,90]               [,91]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,92]               [,93]               [,94]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,95]             

In [119]:
library(dplyr)
dat.dplyr5 <- dat.base5 %>% mutate(weight_rank=ifelse(weight>=m,2,0))
t(dat.dplyr5$weight_rank)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 2    2    2    2    2    2    2    2    2    2     ⋯     0     0     0    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 0     0     0     0     0     0     0

In [120]:
library(dplyr)
dat.dplyr6 <- dat.base5 %>% mutate(weight_cut=cut(dat.base5$weight, breaks=q))
t(dat.dplyr6$weight_cut)

[,1]               [,2]                [,3]              
[1,] (2.8e+03,3.61e+03] (3.61e+03,5.14e+03] (2.8e+03,3.61e+03]
     [,4]               [,5]               [,6]               
[1,] (2.8e+03,3.61e+03] (2.8e+03,3.61e+03] (3.61e+03,5.14e+03]
     [,7]                [,8]                [,9]               
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,10]               [,11]              [,12]              
[1,] (3.61e+03,5.14e+03] (2.8e+03,3.61e+03] (3.61e+03,5.14e+03]
     [,13]               [,14]              [,15]             
[1,] (3.61e+03,5.14e+03] (2.8e+03,3.61e+03] (2.22e+03,2.8e+03]
     [,16]              [,17]              [,18]             
[1,] (2.8e+03,3.61e+03] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03]
     [,19]               [,20]               [,21]             
[1,] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03] (2.22e+03,2.8e+03]
     [,22]              [,23]              [,24]             
[1,] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03]
     [,25]              [,26]               [,27]              
[1,] (2.22e+03,2.8e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,28]               [,29]               [,30]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (1.61e+03,2.22e+03]
     [,31]              [,32]              [,33]              
[1,] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03] (1.61e+03,2.22e+03]
     [,34]              [,35]              [,36]             
[1,] (2.22e+03,2.8e+03] (2.8e+03,3.61e+03] (2.8e+03,3.61e+03]
     [,37]              [,38]              [,39]              
[1,] (2.8e+03,3.61e+03] (2.8e+03,3.61e+03] (3.61e+03,5.14e+03]
     [,40]               [,41]               [,42]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,43]               [,44]               [,45]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,46]              [,47]              [,48]             
[1,] (2.8e+03,3.61e+03] (2.22e+03,2.8e+03] (2.8e+03,3.61e+03]
     [,49]              [,50]               [,51]              
[1,] (2.8e+03,3.61e+03] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03]
     [,52]               [,53]               [,54]               [,55]       
[1,] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03] (0,1.61e+03]
     [,56]               [,57]               [,58]             
[1,] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03] (2.22e+03,2.8e+03]
     [,59]               [,60]              [,61]             
[1,] (1.61e+03,2.22e+03] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03]
     [,62]              [,63]               [,64]              
[1,] (2.22e+03,2.8e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,65]               [,66]               [,67]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,68]               [,69]               [,70]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,71]               [,72]              [,73]              
[1,] (3.61e+03,5.14e+03] (2.22e+03,2.8e+03] (3.61e+03,5.14e+03]
     [,74]               [,75]               [,76]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,77]              [,78]              [,79]             
[1,] (2.8e+03,3.61e+03] (2.22e+03,2.8e+03] (2.8e+03,3.61e+03]
     [,80]               [,81]              [,82]             
[1,] (1.61e+03,2.22e+03] (2.22e+03,2.8e+03] (2.22e+03,2.8e+03]
     [,83]              [,84]               [,85]              
[1,] (2.22e+03,2.8e+03] (1.61e+03,2.22e+03] (1.61e+03,2.22e+03]
     [,86]               [,87]               [,88]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,89]               [,90]               [,91]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,92]               [,93]               [,94]              
[1,] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
     [,95]             

In [121]:
t(as.integer(dat.dplyr6$weight_cut))

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] 4    5    4    4    4    5    5    5    5    5     ⋯     3     4     3    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 3     4     3     2     3     3     3

In [94]:
summary(dat.dplyr6)

      mpg           cylinder      displacement    horsepower       
 Min.   : 9.00   Min.   :3.000   Min.   : 68.0   Length:398        
 1st Qu.:17.50   1st Qu.:4.000   1st Qu.:104.2   Class :character  
 Median :23.00   Median :4.000   Median :148.5   Mode  :character  
 Mean   :23.51   Mean   :5.455   Mean   :193.4                     
 3rd Qu.:29.00   3rd Qu.:8.000   3rd Qu.:262.0                     
 Max.   :46.60   Max.   :8.000   Max.   :455.0                     
     weight      acceleration        year           origin     
 Min.   :1613   Min.   : 8.00   Min.   :70.00   Min.   :1.000  
 1st Qu.:2224   1st Qu.:13.82   1st Qu.:73.00   1st Qu.:1.000  
 Median :2804   Median :15.50   Median :76.00   Median :1.000  
 Mean   :2970   Mean   :15.57   Mean   :76.01   Mean   :1.573  
 3rd Qu.:3608   3rd Qu.:17.18   3rd Qu.:79.00   3rd Qu.:2.000  
 Max.   :5140   Max.   :24.80   Max.   :82.00   Max.   :3.000  
     name            weight_rank                   weight_cut 
 Length:398  

In [95]:
t(dat.dplyr6)

[,1]                      [,2]                [,3]              
mpg          18.0                      15.0                18.0              
cylinder     8                         8                   8                 
displacement 307.0                     350.0               318.0             
horsepower   130                       165                 150               
weight       3504                      3693                3436              
acceleration 12.0                      11.5                11.0              
year         70                        70                  70                
origin       1                         1                   1                 
name         chevrolet chevelle malibu buick skylark 320   plymouth satellite
weight_rank  1                         1                   1                 
weight_cut   (2.8e+03,3.61e+03]        (3.61e+03,5.14e+03] (2.8e+03,3.61e+03]
             [,4]               [,5]               [,6]               
mpg          16.0               17.0               15.0               
cylinder     8                  8                  8                  
displacement 304.0              302.0              429.0              
horsepower   150                140                198                
weight       3433               3449               4341               
acceleration 12.0               10.5               10.0               
year         70                 70                 70                 
origin       1                  1                  1                  
name         amc rebel sst      ford torino        ford galaxie 500   
weight_rank  1                  1                  1                  
weight_cut   (2.8e+03,3.61e+03] (2.8e+03,3.61e+03] (3.61e+03,5.14e+03]
             [,7]                [,8]                [,9]               
mpg          14.0                14.0                14.0               
cylinder     8                   8                   8                  
displacement 454.0               440.0               455.0              
horsepower   220                 215                 225                
weight       4354                4312                4425               
acceleration  9.0                 8.5                10.0               
year         70                  70                  70                 
origin       1                   1                   1                  
name         chevrolet impala    plymouth fury iii   pontiac catalina   
weight_rank  1                   1                   1                  
weight_cut   (3.61e+03,5.14e+03] (3.61e+03,5.14e+03] (3.61e+03,5.14e+03]
             [,10]               [,11] [,12]                     
mpg          15.0                ⋯     26.0                      
cylinder     8                   ⋯     4                         
displacement 390.0               ⋯     156.0                     
horsepower   190                 ⋯     92                        
weight       3850                ⋯     2585                      
acceleration  8.5                ⋯     14.5                      
year         70                  ⋯     82                        
origin       1                   ⋯     1                         
name         amc ambassador dpl  ⋯     chrysler lebaron medallion
weight_rank  1                   ⋯     0                         
weight_cut   (3.61e+03,5.14e+03] ⋯     (2.22e+03,2.8e+03]        
             [,13]              [,14]              [,15]             
mpg          22.0               32.0               36.0              
cylinder     6                  4                  4                 
displacement 232.0              144.0              135.0             
horsepower   112                96                 84                
weight       2835               2665               2370              
acceleration 14.7               13.9               13.0              
year         82                 82                 82              

In [116]:
sz <- c(as.integer(count(dat.dplyr6)))
rk <- c('a','b','c','d','e','f')
dat.dplyr6$weight_alpha_rank <- 'NULL'
for (i in 1:sz){
    dat.dplyr6$weight_alpha_rank[i] <- rk[as.integer(dat.dplyr6$weight_cut)[i]+1]
}
t(dat.dplyr6$weight_alpha_rank)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] e    f    e    e    e    f    f    f    f    f     ⋯     d     e     d    
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] d     e     d     c     d     d     d

In [110]:
summary(dat.dplyr6)

      mpg           cylinder      displacement    horsepower       
 Min.   : 9.00   Min.   :3.000   Min.   : 68.0   Length:398        
 1st Qu.:17.50   1st Qu.:4.000   1st Qu.:104.2   Class :character  
 Median :23.00   Median :4.000   Median :148.5   Mode  :character  
 Mean   :23.51   Mean   :5.455   Mean   :193.4                     
 3rd Qu.:29.00   3rd Qu.:8.000   3rd Qu.:262.0                     
 Max.   :46.60   Max.   :8.000   Max.   :455.0                     
     weight      acceleration        year           origin     
 Min.   :1613   Min.   : 8.00   Min.   :70.00   Min.   :1.000  
 1st Qu.:2224   1st Qu.:13.82   1st Qu.:73.00   1st Qu.:1.000  
 Median :2804   Median :15.50   Median :76.00   Median :1.000  
 Mean   :2970   Mean   :15.57   Mean   :76.01   Mean   :1.573  
 3rd Qu.:3608   3rd Qu.:17.18   3rd Qu.:79.00   3rd Qu.:2.000  
 Max.   :5140   Max.   :24.80   Max.   :82.00   Max.   :3.000  
     name            weight_rank                   weight_cut 
 Length:398  

In [111]:
# 범주형자료로 변경
dat.dplyr6$weight_alpha_rank <- as.factor(dat.dplyr6$weight_alpha_rank)

In [112]:
summary(dat.dplyr6)

      mpg           cylinder      displacement    horsepower       
 Min.   : 9.00   Min.   :3.000   Min.   : 68.0   Length:398        
 1st Qu.:17.50   1st Qu.:4.000   1st Qu.:104.2   Class :character  
 Median :23.00   Median :4.000   Median :148.5   Mode  :character  
 Mean   :23.51   Mean   :5.455   Mean   :193.4                     
 3rd Qu.:29.00   3rd Qu.:8.000   3rd Qu.:262.0                     
 Max.   :46.60   Max.   :8.000   Max.   :455.0                     
     weight      acceleration        year           origin     
 Min.   :1613   Min.   : 8.00   Min.   :70.00   Min.   :1.000  
 1st Qu.:2224   1st Qu.:13.82   1st Qu.:73.00   1st Qu.:1.000  
 Median :2804   Median :15.50   Median :76.00   Median :1.000  
 Mean   :2970   Mean   :15.57   Mean   :76.01   Mean   :1.573  
 3rd Qu.:3608   3rd Qu.:17.18   3rd Qu.:79.00   3rd Qu.:2.000  
 Max.   :5140   Max.   :24.80   Max.   :82.00   Max.   :3.000  
     name            weight_rank                   weight_cut 
 Length:398  